### ISSUE TITLE
[FEATURE] To add Mentors Section on Website

### ISSUE THREAD

**Issue by ramxcodes** [Ashpara10/acm-website#30]
# Problem:
The website currently has a **Team** section, but there is no **Mentors** section. This is a missing feature, especially if mentorship is part of the offering. Having a dedicated Mentors section would highlight the guidance and support available, and enhance user trust and engagement.
![image](https://github.com/user-attachments/assets/f7baebfa-2f9c-4b9d-95b3-059d302bd522)

# Proposed Fix:
1. **Design and Layout**: Implement a new section following a similar style to the Team section. This should include mentor names, bios, photos, and roles.
3. **Frontend**: Create the necessary UI components to display mentor information.
4. **Testing**: Verify that the Mentors section is responsive across devices and integrates smoothly into the website's design.

#### Tasks:
- [x] Design and mockup for Mentors section
- [x] Frontend implementation for displaying mentor details
- [x] Test and deploy

@Ashpara10  Please assign this issue to me and add hacktoberfest label to it.

Thanks & Regards,
Ramkrishna Swarnkar

**Comment by Atharv-110** [comment]
@ramxcodes Is this issue completed?
